site:
  title: Redpanda Docs
  start_page: redpanda:get-started:intro-to-events.adoc
  url: https://gentle-torte-7343b2.netlify.app
urls:
  html_extension_style: indexify
  redirect_facility: netlify
  latest_version_segment: ''
content:
  sources:
  - url: .
    branches: HEAD
    start_paths: site-root, home
  - url: https://github.com/JakeSCahill/redpanda-docs-antora
    branches: [v*]
  - url: https://github.com/JakeSCahill/redpanda-cloud-docs
    branches: main
ui:
  bundle:
    url: https://github.com/JakeSCahill/redpanda-docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
  # Antora settings
    source-highlighter: ~
    tabs-sync-option: true
    idprefix: ''
    idseparator: '-'
    page-pagination: true
    experimental: true
  # Global variables
    latest-console-version: 2.2.2@
  # Glossary
    glossary-tooltip: 'data-tippy-content'
    terms:
    - term: tatting
      definition: test
      link: https://www.google.com
  extensions:
  - '@asciidoctor/tabs'
  - './macros/glossary.js'
antora:
  extensions:
  - './extensions/version-fetcher/set-latest-version.js'

