site:
  title: Redpanda Docs
  start_page: home:ROOT:index.adoc
  url: http://localhost:5000
content:
  sources:
  - url: https://github.com/redpanda-data/documentation
    branches: playbook
    start_paths: site-search, home, api
  - url: ../local-docs-directory
    branches: HEAD
ui:
  bundle:
    url: https://github.com/JakeSCahill/redpanda-docs-ui/releases/download/beta-ui/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
  extensions:
  - '@asciidoctor/tabs'
  - 'node_modules/antora-extensions-and-macros/macros/glossary.js'
  - 'node_modules/antora-extensions-and-macros/macros/config-ref.js'
  - 'node_modules/antora-extensions-and-macros/macros/helm-ref.js'
antora:
  extensions:
  - 'node_modules/antora-extensions-and-macros/extensions/version-fetcher/set-latest-version.js'
  - 'node_modules/antora-extensions-and-macros/extensions/algolia-indexer/index.js'
  - 'node_modules/antora-extensions-and-macros/extensions/unlisted-pages.js'
  - 'node_modules/antora-extensions-and-macros/extensions/replace-attributes-in-attachments.js'
  - 'node_modules/antora-extensions-and-macros/extensions/add-global-attributes.js'

